accessing-csv
readCsvAllRecords

	^ self readCsvRecords: #(#objectid: #id_0: #iso: #name_0: #id_1: #name_1: #varname_1: #nl_name_1: #hasc_1: #cc_1: #type_1: #engtype_1: #validfr_1: #validto_1: #remarks_1: 
#id_2: #name_2: #varname_2: #nl_name_2: #hasc_2: #cc_2: #type_2: #engtype_2: #validfr_2: #validto_2: #remarks_2: 
#id_3: #name_3: #varname_3: #nl_name_3: #hasc_3: #type_3: #engtype_3: #validfr_3: #validto_3: #remarks_3: 
#id_4: #name_4: #varname_4: #type_4: #engtype_4: #type_4: #engtype_4: #validfr_4: #validto_4: #remarks_4: 
#id_5: #name_5: #type_5: #engtype_5: 
#shape_leng: #shape_area: )